# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.
from snakemake.utils import min_version
min_version("6.0")
module af3_workflow:
    snakefile: github("ntnn19/AlphaFold3_workflow", path="workflow/Snakefile", branch="dev")

# load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"


# load rules
# -----------------------------------------------------
use rule * from af3_workflow as af3_workflow_*
include: "rules/common.smk"
include: "rules/process_reads.smk"


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# target rules
# -----------------------------------------------------
rule all:
    default_target: True
    input:
        "results/done.txt",
